[build]
  command = "pnpm install && pnpm run build:client"
  functions = "netlify/functions"
  publish = "dist/client"

[functions]
  external_node_modules = ["express", "cloudinary"]
  node_bundler = "esbuild"
  included_files = ["server/**", "shared/**"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
